-- 코드를 작성해주세요
-- 2024-11-01
SELECT
    A.ID,
    CASE WHEN A.RANKS / A.TOTAL_COUNT <= 0.25 THEN 'CRITICAL'
         WHEN A.RANKS / A.TOTAL_COUNT <= 0.5 THEN 'HIGH'
         WHEN A.RANKS / A.TOTAL_COUNT <= 0.75 THEN 'MEDIUM'
         ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT
          *,
          RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKS,
          COUNT(*) OVER() AS TOTAL_COUNT
      FROM ECOLI_DATA) AS A
ORDER BY ID;