-- 코드를 입력하세요
-- 2024-11-26
# SELECT HISTORY_ID, SUM(DATEDIFFZ * DAILY_FEE) AS FEE
# FROM () AS A
# GROUP BY HISTORY_ID
# ORDER BY FEE DESC, HISTORY_ID DESC;

WITH TEST AS (
    SELECT
    HISTORY_ID,
    CAR_TYPE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_PERIOD,
    DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING(CAR_ID)
)

SELECT
HISTORY_ID,
CASE WHEN RENTAL_PERIOD >= CAST(DURATION_TYPE UNSIGNED) THEN SUM(DAILY_FEE * (1 - ))
FROM TEST
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING(CAR_TYPE)
WHERE CAR_TYPE = '트럭'
GROUP BY HISTORY_ID