-- 코드를 입력하세요
-- 2024-11-27
WITH
SUB_QUERY1 AS (
    SELECT
    HISTORY_ID,
    CAR_TYPE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS RENTAL_PERIOD,
    DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING(CAR_ID)
),
SUB_QUERY2 AS (
    SELECT
    CAR_TYPE,
    CAST(DURATION_TYPE AS UNSIGNED) AS DURATION_TYPE,
    DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
),
SUB_QUERY3 AS (
    SELECT
    HISTORY_ID,
    CASE WHEN RENTAL_PERIOD >= DURATION_TYPE THEN CAST(DAILY_FEE * RENTAL_PERIOD * (1 - DISCOUNT_RATE / 100) AS UNSIGNED)
         ELSE DAILY_FEE * RENTAL_PERIOD
    END AS FEE
    FROM SUB_QUERY1
    JOIN SUB_QUERY2 USING(CAR_TYPE)
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, MIN(FEE) AS FEE
FROM SUB_QUERY3
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;