-- 코드를 작성해주세요
-- 2024-12-11
WITH
SUB_QUERY1 AS
(
    SELECT *
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
SUB_QUERY2 AS
(
    SELECT DISTINCT A.ID
    FROM DEVELOPERS AS A
    JOIN SUB_QUERY1 AS B
    ON B.CODE & A.SKILL_CODE = B.CODE
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (SELECT * FROM SUB_QUERY2)
ORDER BY ID;