-- 코드를 작성해주세요
-- 2024-12-28
WITH
SUB_QUERY1 AS
(
    SELECT ID, EMAIL, GROUP_CONCAT(B.NAME) AS NAME, GROUP_CONCAT(B.CATEGORY) AS CATEGORY
    FROM DEVELOPERS AS A
    JOIN SKILLCODES AS B
    ON A.SKILL_CODE & B.CODE = B.CODE
    GROUP BY ID, EMAIL
),
SUB_QUERY2 AS
(
    SELECT
    CASE
        WHEN CATEGORY LIKE '%Front End%' AND NAME LIKE '%Python%' THEN 'A'
        WHEN NAME LIKE '%C#%' THEN 'B'
        WHEN CATEGORY LIKE '%Front End%' THEN 'C'
    END AS GRADE,
    A.ID,
    A.EMAIL
    FROM SUB_QUERY1 AS A
)

SELECT *
FROM SUB_QUERY2
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;