-- 코드를 입력하세요
-- 2024-11-03
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS AS A
JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
AND A.SEX_UPON_INTAKE LIKE '%Intact%'
AND B.SEX_UPON_OUTCOME REGEXP 'Neutered|Spayed'
ORDER BY ANIMAL_ID;