SELECT   TO_NUMBER(TO_CHAR(DATETIME, 'FMHH24')) AS HOUR
       , COUNT(*)
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'FMHH24')
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'FMHH24')) BETWEEN 9 AND 19
ORDER BY HOUR;
