-- 코드를 작성해주세요
-- 2024-10-14
SELECT SUM(B.SCORE) AS SCORE, B.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
FROM HR_EMPLOYEES AS A
NATURAL JOIN HR_GRADE AS B
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;