-- 코드를 입력하세요
WITH CUSTOM_REST_REVIEW AS
 (
    SELECT
            MEMBER_ID
    FROM
            REST_REVIEW
    GROUP BY
            MEMBER_ID
    ORDER BY
            COUNT(*) DESC
    FETCH
            FIRST ROWS ONLY
 )
SELECT
        MEMBER_NAME
      , REVIEW_TEXT
      , TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM
        REST_REVIEW
INNER JOIN
        CUSTOM_REST_REVIEW
        USING(MEMBER_ID)
INNER JOIN
        MEMBER_PROFILE
        USING(MEMBER_ID)
ORDER BY
        REVIEW_DATE, REVIEW_TEXT;
