SELECT
        A.APNT_NO
      , (SELECT PT_NAME FROM PATIENT WHERE PT_NO = A.PT_NO) AS PT_NAME
      , A.PT_NO
      , A.MCDP_CD
      , (SELECT DR_NAME FROM DOCTOR WHERE DR_ID = A.MDDR_ID) AS DR_NAME
      , A.APNT_YMD
FROM
        APPOINTMENT A
WHERE
        TO_CHAR(A.APNT_YMD, 'YYYY-MM-DD') = '2022-04-13'
AND
        A.APNT_CNCL_YN = 'N'
ORDER BY
        APNT_YMD;
