-- 코드를 입력하세요
WITH CUSTOM_JULY AS
 (
    SELECT
            FLAVOR
          , SUM(TOTAL_ORDER) AS JULY_TOTAL_ORDER
    FROM
            JULY
    GROUP BY
            FLAVOR
 )
SELECT
        FLAVOR
FROM
        FIRST_HALF
INNER JOIN
        CUSTOM_JULY
        USING(FLAVOR)
ORDER BY
        (TOTAL_ORDER + JULY_TOTAL_ORDER) DESC
        FETCH NEXT 3 ROWS ONLY;
