-- 코드를 입력하세요
SELECT
        AUTHOR_ID
      , AUTHOR_NAME
      , CATEGORY
      , SUM(SALES * PRICE) AS TOTAL_SALES
FROM
        BOOK_SALES
INNER JOIN
        BOOK
        USING(BOOK_ID)
INNER JOIN
        AUTHOR
        USING(AUTHOR_ID)
WHERE
        TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY
        AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY
        AUTHOR_ID, CATEGORY DESC;
