SELECT
        A.ANIMAL_ID
      , A.ANIMAL_TYPE
      , A.NAME
FROM
        ANIMAL_INS A
      , ANIMAL_OUTS B
WHERE
        A.ANIMAL_ID = B.ANIMAL_ID
AND
        A.SEX_UPON_INTAKE LIKE 'Intact%'
AND
        REGEXP_LIKE(B.SEX_UPON_OUTCOME, 'Neutered|Spayed')
ORDER BY
        A.ANIMAL_ID;
