-- 코드를 입력하세요
WITH CUSTOM_USER_INFO AS
    (
        SELECT
            *
        FROM
            USER_INFO
        WHERE
            TO_CHAR(JOINED, 'YYYY') = '2021'
    )
   , CUSTOM_ONLINE_SALE AS
    (
        SELECT
            USER_ID
             , TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')) AS YEAR
   , TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH
FROM
    ONLINE_SALE
    )

SELECT
    A.YEAR
     , A.MONTH
     , COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS
     , ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(*) FROM CUSTOM_USER_INFO), 1) AS PUCHASED_RATIO
FROM
    CUSTOM_ONLINE_SALE A
        INNER JOIN
    CUSTOM_USER_INFO B ON A.USER_ID = B.USER_ID
GROUP BY
    A.YEAR, A.MONTH
ORDER BY
    YEAR, MONTH;
